name: Build & Test
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  cpp-20-debug:
    name: C++ 20 (Debug)
    uses: karmakrafts/workflows/.github/workflows/cpp.yml@master
    with:
      build_type: "Debug"
      std_version: 20
